# Generated by Django 5.0.14 on 2026-05-04 13:20

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Seriya raqami')),
                ('installed_at', models.DateField(default=datetime.date.today, verbose_name="O'rnatilgan sana")),
                ('tariff_mode', models.CharField(choices=[('single', 'Bir vaqtli (oddiy)'), ('double', 'Ikki vaqtli (kun/tun)')], default='single', max_length=10, verbose_name='Tarif rejimi')),
                ('initial_reading', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Boshlang'ich ko'rsatkich")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('account_number', models.CharField(blank=True, max_length=30, verbose_name='Shaxsiy hisob raqami')),
            ],
            options={
                'verbose_name': 'Hisoblagich',
                'verbose_name_plural': 'Hisoblagichlar',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('icon', models.CharField(default='bi-lightning', max_length=50, verbose_name='Bootstrap Icon nomi')),
                ('color', models.CharField(default='#0066ff', max_length=7, verbose_name='HEX rang')),
                ('unit', models.CharField(default='kVt·s', max_length=20, verbose_name="O'lchov birligi")),
                ('has_meter', models.BooleanField(default=True, verbose_name='Hisoblagichli')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SmsCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('code', models.CharField(max_length=6, verbose_name='Kod')),
                ('purpose', models.CharField(choices=[('register', "Ro'yxatdan o'tish"), ('reset', 'Parol tiklash'), ('confirm', 'Tasdiqlash')], default='register', max_length=10, verbose_name='Maqsad')),
                ('is_used', models.BooleanField(default=False, verbose_name='Ishlatilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SMS kod',
                'verbose_name_plural': 'SMS kodlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Telefon')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('region', models.CharField(blank=True, default='Toshkent', max_length=100, verbose_name='Hudud')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('1250000.00'), max_digits=12, verbose_name="Balans (so'm)")),
                ('pin_code', models.CharField(blank=True, max_length=4, verbose_name='PIN kod')),
                ('notify_threshold_percent', models.IntegerField(default=30, verbose_name='Sarflash ogohlantirish chegarasi (%)')),
                ('language', models.CharField(choices=[('uz', "O'zbek (lotin)"), ('uz-cyrl', "O'zbek (kirill)"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=10, verbose_name='Til')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('uzcard', 'UzCard'), ('humo', 'Humo'), ('visa', 'Visa'), ('mastercard', 'MasterCard')], default='uzcard', max_length=15, verbose_name='Turi')),
                ('number_last4', models.CharField(max_length=4, verbose_name='Oxirgi 4 raqam')),
                ('holder_name', models.CharField(max_length=100, verbose_name='Egasining ismi')),
                ('expiry_month', models.IntegerField(verbose_name='Amal qilish oyi')),
                ('expiry_year', models.IntegerField(verbose_name='Amal qilish yili')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('5000000'), max_digits=12, verbose_name="Balans (so'm)")),
                ('is_primary', models.BooleanField(default=False, verbose_name='Asosiy')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'Karta',
                'verbose_name_plural': 'Kartalar',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Avvalgi ko'rsatkich")),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Joriy ko'rsatkich")),
                ('consumption', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sarfi')),
                ('night_consumption', models.DecimalField(decimal_places=2, default=0, help_text='Faqat 2 vaqtli tarifda', max_digits=10, verbose_name='Tungi sarf')),
                ('reading_date', models.DateField(default=datetime.date.today, verbose_name='Sana')),
                ('image', models.ImageField(blank=True, null=True, upload_to='meter_readings/', verbose_name='Hisoblagich rasmi')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('is_anomaly', models.BooleanField(default=False, verbose_name='Anomaliya')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.meter', verbose_name='Hisoblagich')),
            ],
            options={
                'verbose_name': "Hisoblagich ko'rsatkichi",
                'verbose_name_plural': "Hisoblagich ko'rsatkichlari",
                'ordering': ['-reading_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('severity', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori')], default='medium', max_length=10, verbose_name='Darajasi')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Hal qilingan')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Aniqlangan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.meter', verbose_name='Hisoblagich')),
                ('reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.meterreading', verbose_name='Yozuv')),
            ],
            options={
                'verbose_name': 'Anomaliya',
                'verbose_name_plural': 'Anomaliyalar',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('message', models.TextField(verbose_name='Matn')),
                ('type', models.CharField(choices=[('payment', "To'lov"), ('reminder', 'Eslatma'), ('anomaly', 'Anomaliya'), ('tariff', 'Tarif'), ('system', 'Tizim')], default='system', max_length=15, verbose_name='Turi')),
                ('icon', models.CharField(default='bi-bell', max_length=50, verbose_name='Ikon')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='Havola')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: "Asosiy uy"', max_length=100, verbose_name='Nomi')),
                ('address', models.CharField(max_length=255, verbose_name="To'liq manzil")),
                ('region', models.CharField(default='Toshkent', max_length=100, verbose_name='Hudud')),
                ('rooms', models.IntegerField(default=2, verbose_name='Xonalar soni')),
                ('area_sqm', models.DecimalField(decimal_places=2, default=60, max_digits=6, verbose_name='Maydoni (m²)')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Asosiy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'Manzil',
                'verbose_name_plural': 'Manzillar',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='meter',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='core.property', verbose_name='Manzil'),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_month', models.IntegerField(default=25, verbose_name='Oyning kuni')),
                ('message', models.CharField(blank=True, max_length=200, verbose_name='Xabar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.property', verbose_name='Manzil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='Xizmat')),
            ],
            options={
                'verbose_name': 'Eslatma',
                'verbose_name_plural': 'Eslatmalar',
            },
        ),
        migrations.AddField(
            model_name='meter',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meters', to='core.service', verbose_name='Xizmat'),
        ),
        migrations.CreateModel(
            name='AutoPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_month', models.IntegerField(default=10, verbose_name='Oyning kuni')),
                ('max_amount', models.DecimalField(decimal_places=2, default=Decimal('500000'), max_digits=12, verbose_name='Maksimal summa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('last_run', models.DateField(blank=True, null=True, verbose_name='Oxirgi ishga tushgan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_payments', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.card', verbose_name='Karta')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property', verbose_name='Manzil')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='Xizmat')),
            ],
            options={
                'verbose_name': "Avtomatik to'lov",
                'verbose_name_plural': "Avtomatik to'lovlar",
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='Nomi')),
                ('tariff_type', models.CharField(choices=[('single', 'Bir vaqtli'), ('day', 'Kunduzgi'), ('night', 'Tungi')], default='single', max_length=10, verbose_name='Turi')),
                ('region', models.CharField(default='Toshkent', max_length=100, verbose_name='Hudud')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Birlik narxi (so'm)")),
                ('valid_from', models.DateField(default=datetime.date.today, verbose_name='Boshlangan sana')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Tugagan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='core.service', verbose_name='Xizmat')),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tariflar',
                'ordering': ['service', '-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Summa (so'm)")),
                ('status', models.CharField(choices=[('success', 'Muvaffaqiyatli'), ('pending', 'Kutilmoqda'), ('failed', 'Bekor qilingan')], default='success', max_length=10, verbose_name='Holat')),
                ('receipt_number', models.CharField(max_length=20, unique=True, verbose_name='Kvitansiya raqami')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('account_number', models.CharField(blank=True, max_length=30, verbose_name='Shaxsiy hisob')),
                ('is_auto', models.BooleanField(default=False, verbose_name="Avtomatik to'lov")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.card', verbose_name='Karta')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.property', verbose_name='Manzil')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.service', verbose_name='Xizmat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Tranzaksiya',
                'verbose_name_plural': 'Tranzaksiyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', "Faqat ko'rish"), ('editor', 'Tahrirlash')], default='viewer', max_length=10, verbose_name='Rol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_member_in', to=settings.AUTH_USER_MODEL, verbose_name="A'zo")),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_invites', to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='core.property', verbose_name='Manzil')),
            ],
            options={
                'verbose_name': "Oila a'zosi",
                'verbose_name_plural': "Oila a'zolari",
                'unique_together': {('member', 'property')},
            },
        ),
    ]
