# Generated by Django 5.0.14 on 2026-05-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='apartment',
            field=models.CharField(blank=True, max_length=20, verbose_name='Kvartira raqami'),
        ),
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tuman/Shahar'),
        ),
        migrations.AddField(
            model_name='property',
            name='house_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Uy raqami'),
        ),
        migrations.AddField(
            model_name='property',
            name='mahalla',
            field=models.CharField(blank=True, max_length=150, verbose_name='Mahalla / MFY'),
        ),
        migrations.AddField(
            model_name='property',
            name='street',
            field=models.CharField(blank=True, max_length=150, verbose_name="Ko'cha"),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name="To'liq manzil"),
        ),
        migrations.AlterField(
            model_name='property',
            name='region',
            field=models.CharField(default='Toshkent shahri', max_length=100, verbose_name='Viloyat'),
        ),
    ]
