# Generated by Django 5.0.14 on 2026-05-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_property_apartment_property_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='region',
            field=models.CharField(default='Toshkent shahri', max_length=100, verbose_name='Hudud'),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, default='Toshkent shahri', max_length=100, verbose_name='Hudud'),
        ),
    ]
